#/bin/sh

set -e

psql -v ON_ERROR_STOP=1 \
     -v APP_USR=$USER_LOGIN -v APP_PASS=$USER_PASSWORD \
     -v OWN_USR=$ADMIN_LOGIN -v OWN_PASS=$ADMIN_PASSWORD \
     -v RO_USR=$USER_RO -v RW_USR=$USER_RW \
     --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE :"APP_USR";
    ALTER ROLE :"APP_USR" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD :'APP_PASS';
    CREATE ROLE :"RO_USR";
    ALTER ROLE :"RO_USR" WITH NOSUPERUSER NOINHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS;
    CREATE ROLE :"RW_USR";
    ALTER ROLE :"RW_USR" WITH NOSUPERUSER NOINHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS;
    CREATE ROLE :"OWN_USR";
    ALTER ROLE :"OWN_USR" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD :'OWN_PASS' VALID UNTIL 'infinity';
    ALTER DATABASE "$POSTGRES_DB" OWNER TO :"OWN_USR";
    CREATE EXTENSION "pgcrypto";
EOSQL